## Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2 

array([2, 4, 6, 8])

In [6]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [8]:
a ** 2 

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
# Take sine of all values
np.sin(a)
# or a single value
np.sin(a[1])

0.9092974268256817

## Linear Algebra

In [10]:
e = np.ones((2,3))
print(e)

r = np.full((3,2), 2)
print(r)

np.matmul(r, e)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [11]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [12]:
# For more details: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html