## Reorganizing Arrays

In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, '\nand the shape',before.shape)

[[1 2 3 4]
 [5 6 7 8]] 
and the shape (2, 4)


In [3]:
after = before.reshape((2,2,2))
print(after, '\nand the shape', after.shape)
# This will work when the size matches each other

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
and the shape (2, 2, 2)


In [4]:
after2 = before.reshape((2,3))
print(after2, '\nand the shape', after2.shape)

ValueError: cannot reshape array of size 8 into shape (2,3)

## Vertically Stacking

In [5]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

## Horizontal Stack

In [6]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])